config/routes.rb
ThirtyDayList::Application.routes.draw do
  devise_for :users

  resources :items, :only => [:index, :new, :create]

  get 'privacy_policy' => 'public#privacy_policy', :as => :privacy_policy
  get 'about' => 'public#about', :as => :about

  root :to => 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :rcoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  layout 'public'

  protect_from_forgery

  protected

  expose(:title) { @title || '30daylist.com' }
  expose(:current_primary_tab) { @current_primary_tab || controller_name }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @current_primary_tab = 'Home'
  end

  def create
    item[:user_id] = current_user.id
    if item.save
      flash[:notice] = "#{item.name} was added to your list."
      redirect_to root_path
    else
      render :action => "new"
    end

  end

  private

  expose(:my_items) { Item.where(:user_id => current_user.id).order('items.created_at DESC') }
  expose(:item)

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def home_page
    @current_primary_tab = 'Home'
    if current_user.present?
      render 'item/index'
    end
  end

  def about
    @current_primary_tab = 'About'
  end

  protected

  expose(:current_primary_tab) { @current_primary_tab }
end

app/helpers/application_helper.rb
module ApplicationHelper

  def generate_primary_navigation
    content_tag(:ul, nav_entries(primary_nav_fields, nav_map[current_primary_tab] || current_primary_tab))
  end

  protected

  def nav_entries(entries, match_tab)
    ''.html_safe.tap do |items|
      entries.sort_by {|f| f[:order]}.each do |field|
        html_options = field[:title] == match_tab.to_s ? {:class => 'current'} : {}
        html_options[:title] = field[:title]
        item_content = field[:path].blank? ? field[:title] : link_to(field[:title], field[:path], html_options)
        items << content_tag(:li, item_content)
      end
    end
  end

  def primary_nav_fields
    [].tap do |fields|
      fields << {:title => 'Home', :path => root_path, :order => 1}
      fields << {:title => 'About', :path => about_path, :order => 2}
      if current_user.present?
        fields << {:title => 'Sign Out', :path => destroy_user_session_path, :order => 3}
      else
        fields << {:title => 'Sign Up', :path => new_user_registration_path, :order => 3}
        fields << {:title => 'Sign In', :path => new_user_session_path, :order => 4}
      end
    end
  end

  def nav_map
    {
      'registrations' => 'Sign Up',
      'sessions' => 'Sign In'
    }
  end
end

app/helpers/items_helper.rb
module ItemsHelper

  def distance(item)
    if item.created_at < 30.days.ago
      "added #{Time.zone.now.to_date - item.created_at.to_date} days ago"
    else
      "#{(item.created_at.to_date + 30.days - Time.zone.now.to_date).to_i} days to go"
    end
  end
end

app/views/items/index.html.haml
%h1 Welcome To Your List

%p.leadin
  Add an item to it.
= form_for item do |f|
  = f.label :name, 'I want'
  = succeed '.' do
    = f.text_field :name
  = f.submit 'Add it to my list.'

- unless my_items.blank?
  %p Already on your list:
  %ul#items
    - my_items.each do |item|
      %li{:class => (item.created_at > 30.days.ago) ? 'waiting' : 'ready' }
        = item.name
        .when
          = distance(item)
- else
  %p Your list is empty.

app/views/layouts/public.html.haml
!!!
%html{html_attrs(I18n.locale)}
  %head
    %meta(http-equiv='Content-Type' content='text/html;charset=utf-8')
    %meta(http-equiv='Content-Script-Type' content='text/javascript')
    - if protect_against_forgery?
      %meta(name='authenticity_token' content=form_authenticity_token)
    = stylesheet_link_tag 'default'
    = javascript_include_tag :defaults
    %title= title
    = yield :head
  %body
    #upbg
      #outer
        #header
          #headercontent
            %h1 30daylist.com
        #menu
          =generate_primary_navigation
        #menubottom
        #flash
          - flash.each do |name, msg|
            %div(class=name)
              .close_button{:onclick => "$('#flash .#{name}').fadeOut(500);"}
                Close [X]
              = msg
        #content
          = yield
        #footer
          .left &copy; #{Date.today.year} Keller Solutions, All rights reserved.
          .right= link_to 'Privacy Policy', privacy_policy_path